name: hulzzuk CI CD

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  # pull request 시 테스트만 진행
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # 1. 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      # 3. Maven 테스트 실행
      - name: Run test with Maven
        run: mvn test
        
  # push 시 빌드 및 배포
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      # 1. 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      # 3. Maven build (war 파일 생성)
      - name: Clean with maven
        run: mvn clean install

      # 4. war 파일 업로드 (target/*.war)
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hulzzuk-war
          path: target/*.war
  
  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1. 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      # 3. war 다운로드
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: hulzzuk-war
          path: target/
          
      # 4. aws 서버 파일 복사
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with: 
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER_NAME}}
          port: ${{secrets.PORT}}
          source: "target/*.war"
          target: "/app/tomcat/dev/war"
      
      # 5. aws 서버 배포
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER_NAME}}
          port: ${{secrets.PORT}}
          script:  |
            sudo mv /app/tomcat/dev/apache-tomcat-10.1.39/webapps/hulzzuk.war /app/tomcat/dev/war/hulzzuk_backup.war 
            sudo mv /app/tomcat/dev/war/target/hulzzuk-0.0.1-SNAPSHOT.war /app/tomcat/dev/apache-tomcat-10.1.39/webapps/hulzzuk.war
            sudo /app/tomcat/dev/apache-tomcat-10.1.39/bin/./shutdown.sh
            sudo /app/tomcat/dev/apache-tomcat-10.1.39/bin/./startup.sh
